/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package otniel.kevin.abiel.coroutine

/**
 * Thread Utama
 *
 * Saat kita menjalankan sebuah process (aplikasi) Kotlin di JVM, secara otomatis proses tersebut akan jalan di sebuah thread utama
 * Thread utama tersebut bernama main thread (JVM)
 * Saat kita menjalankan process JUnit, JUnit pun berjalan di thread tersendiri
 * Begitu juga jika kita  membuat aplikasi kotlin Android, aplikasi tersebut akan berjalan di sebuah thread
 *
 */

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)

    println("Running in thread ${Thread.currentThread().name}") //Running in thread main (thread bernama main)
}
